Repository Runnect/Runnect-iOS, pull requests merged in 2023-12, with the labels that each got.

#213 [Feat] #194 - 코스 발견 페이지 UI 변경 하였습니다.
  .gitignore
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_plus_button.imageset/Component 125.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_plus_button.imageset/Component 125@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_plus_button.imageset/Component 125@3x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_plus_button.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_plus_button.imageset/plus.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_plus_button.imageset/plus@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_plus_button.imageset/plus@3x.png
  Runnect-iOS/Runnect-iOS/Global/Utils/RNUtils/UserManager.swift
  Runnect-iOS/Runnect-iOS/GoogleSupport/GoogleService-Info.plist
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDetailDto/ResponseDto/UploadedCourseDetailResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDiscoveryDto/ResponseDto/MarathonListResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDiscoveryDto/ResponseDto/PickedMapListResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDiscoveryDto/ResponseDto/TotalPageCountDto.swift
  Runnect-iOS/Runnect-iOS/Network/Router/PublicCourseRouter.swift
  Runnect-iOS/Runnect-iOS/Network/Service/AuthInterceptor.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/AdImageCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/MapCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/MarathonMapCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/MarathonTitleCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/TitleCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseDiscoveryVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseSearchVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CVC/MarathonCourseListCVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/SignIn/VC/SignInSocialLoginVC.swift
Labels: Feat, Refactor

#219 [Feat] #212 - 러닝 기록 상세페이지 메뉴 변경
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordDetailVC.swift
Labels: Chore, Feat, 명진😼

#223 [Feat] #186 - 유저프로필 구현 하였습니다.
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Literal/ColorLiterals.swift
  Runnect-iOS/Runnect-iOS/Global/Literal/FontLiterals.swift
  Runnect-iOS/Runnect-iOS/Global/Supports/SceneDelegate.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDetailDto/ResponseDto/UploadedCourseDetailResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDiscoveryDto/ResponseDto/MarathonListResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDiscoveryDto/ResponseDto/PickedMapListResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/MyPageDto/UserProfileDto.swift
  Runnect-iOS/Runnect-iOS/Network/Router/UserRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/UserProfile/CollectionViewCell/UserInfoCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/UserProfile/CollectionViewCell/UserProgressCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/UserProfile/CollectionViewCell/UserUploadedLabelCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/UserProfile/UserProfileVC.swift
Labels: Feat, 명진😼

#201 [Feat] #199 - 내가 그린 코스 상세 페이지를 변경 하였습니다.
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseStorageDto/ResponseDto/ScrapCourseResponseDto.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/PrivateCourseListView.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningWaitingVC.swift
Labels: Feat, 명진😼

#222 [Refactor] #207 - 서버 통신 함수 리팩토링
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Network/Service/NetworkProvider.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingVC.swift
Labels: Refactor, 소진🍊

#221 [Feat] #214 - 코스그리기 및 업로드 팝업 추가
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomAlertVC.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/RNAlertVC.swift
  Runnect-iOS/Runnect-iOS/Global/Utils/RNUtils/convertLocationObject.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDrawingDto/RequestDto/CourseDrawingRequestDto.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDrawingDto/ResponseDto/CourseDrawingResponseData.swift
  Runnect-iOS/Runnect-iOS/Network/Model/CourseDrawingModel/RNLocationModel.swift
  Runnect-iOS/Runnect-iOS/Network/Router/CourseRouter.swift
  Runnect-iOS/Runnect-iOS/Network/Service/NetworkProvider.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/DepartureSearchVC.swift
Labels: Feat, 소진🍊

#225 [Feat] #224 - 코스발견, 코스보관함, 코스 상세, 유저프로필 1차 QA 진행 하였습니다.
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDiscoveryDto/ResponseDto/MarathonListResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDiscoveryDto/ResponseDto/TotalPageCountDto.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseStorageDto/ResponseDto/PrivateCourseResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Router/CourseRouter.swift
  Runnect-iOS/Runnect-iOS/Network/Router/PublicCourseRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/AdImageCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/MapCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/MarathonMapCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/MarathonTitleCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/TitleCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseDiscoveryVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CVC/MarathonCourseListCVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/PrivateCourseListView.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningWaitingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/UserProfile/CollectionViewCell/UserInfoCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/UserProfile/CollectionViewCell/UserProgressCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/UserProfile/CollectionViewCell/UserUploadedLabelCell.swift
Labels: Del, Feat, Refactor, 명진😼

#231 [Feat] #229 - 코스 상세 스크랩 부분 API 변경으로 인한 코드 추가 구현, 코스 발견 이벤트 추가 작업을 하였습니다.
  Runnect-iOS/Podfile.lock
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDetailDto/ResponseDto/CourseDetailScrapCountDto.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/MarathonMapCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseDiscoveryVC.swift
Labels: Feat, 명진😼

#233 [Setting] #232 - 계정 이전 작업
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Info.plist
Labels: Setting

#227 [Feat] #226 - 코스 발견 피드에서의 이벤트 처리들을 추가 해주었습니다.
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseStorageDto/ResponseDto/PrivateCourseNotUploadedResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/MyPageDto/MyUploadedCourseResponseDto.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseDiscoveryVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseUploadVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/MyCourseSelectVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoVC.swift
Labels: Feat, 명진😼
