Repository Runnect/Runnect-iOS, pull requests merged in 2023-05, with the labels that each got.

#135 [Feat] #130 - 마이페이지 러닝 기록 UI 구현
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Literal/ImageLiterals.swift
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_record_container.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_record_container.imageset/Subtract.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_record_container.imageset/Subtract@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_record_container.imageset/Subtract@3x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_record_container_selected.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_record_container_selected.imageset/Subtract.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_record_container_selected.imageset/Subtract@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_record_container_selected.imageset/Subtract@3x.png
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomNavigationBar.swift
  Runnect-iOS/Runnect-iOS/Network/Model/MyPageModel/GoalRewardInfoModel.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoTableView/ActivityRecordInfoTVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/NicknameEditorVC.swift
Labels: Feat, 재현🐶

#138 [Feat] #136 - 마이페이지 러닝 기록 상세뷰 UI와 삭제 api 연결
  Runnect-iOS/Runnect-iOS/Global/UIComponents/RNAlertVC.swift
  Runnect-iOS/Runnect-iOS/Network/Router/RecordRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoTableView/ActivityRecordInfoTVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoVC.swift
Labels: Feat, 재현🐶

#140 [Feat] #139 - 러닝 기록 수정 페이지 UI 및 api 연결
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomNavigationBar.swift
  Runnect-iOS/Runnect-iOS/Network/Router/RecordRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingHomeVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoVC.swift
Labels: Feat, 재현🐶

#143 [Chore] #141 - 자잘한 수정 사항
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomNavigationBar.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/MyPageDto/MyPageDto.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoTableView/ActivityRecordInfoTVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/SetInfoLayout.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/NicknameEditorVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/PersonalInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/SettingVC.swift
Labels: Chore, 재현🐶

#142 [Feat] #132 - 방문자 플로우 구현
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Extension/UIKit+/UIViewController+.swift
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_heart.imageset/Component 91.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_heart.imageset/Component 91@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_heart.imageset/Component 91@3x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_heart.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_heart.imageset/Property 1=Component 77, Property 2=btn_heart2.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_heart.imageset/Property 1=Component 77, Property 2=btn_heart2@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_heart.imageset/Property 1=Component 77, Property 2=btn_heart2@3x.png
  Runnect-iOS/Runnect-iOS/Global/Supports/SceneDelegate.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomAlertVC.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/ListEmptyView.swift
  Runnect-iOS/Runnect-iOS/Global/Utils/RNUtils/UserManager.swift
  Runnect-iOS/Runnect-iOS/Global/Utils/Toast.swift
  Runnect-iOS/Runnect-iOS/Network/Service/AuthInterceptor.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseDiscoveryVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseSearchVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CVC/CourseListCVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/PersonalInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunTrackingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningRecordVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/SignIn/VC/SignInSocialLoginVC.swift
Labels: Feat, 세진☃️

#137 [Feat ]#134 - 보관함편집기능구현
  Runnect-iOS/Runnect-iOS/Global/Literal/ImageLiterals.swift
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_frame_edit.imageset/Frame 2064.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_frame_edit.imageset/Frame 2064@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_frame_edit.imageset/Frame 2064@3x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_banner1.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_banner1.imageset/ios 1.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_banner2.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_banner2.imageset/ios 2.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_banner3.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_banner3.imageset/ios 3.png
  Runnect-iOS/Runnect-iOS/Network/Router/PublicCourseRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseEditVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/AdImageCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/MapCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/TitleCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseDiscoveryVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/PrivateCourseListView.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/PersoanlInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/TermsOfServiceVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/TabBar/TaBarController.swift
Labels: Feat, 연우🐰

#148 [Fix] #147 - 업로드한 코스 디테일뷰 서버통신 실패 해결
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDetailDto/ResponseDto/UploadedCourseDetailResponseDto.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoVC.swift
Labels: 세진☃️, Fix

#150 [Fix] #144 - 1차 릴리즈 QA 반영
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomBottomSheetVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseDiscoveryVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoTableView/ActivityRecordInfoTVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/GoalRewardInfoCollectionView/GoalRewardInfoCVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/GoalRewardInfoCollectionView/GoalRewardTitleCVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/GoalRewardInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/NicknameEditorVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/SettingVC.swift
Labels: 재현🐶, Fix

#152 [Fix] #151 - 위치 정보 권한 텍스트 변경
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
Labels: 세진☃️, Fix

#156 [Fix] #155 - 보관함 편집모드 애니메이션 버그 수정
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/PrivateCourseListView.swift
Labels: 세진☃️, Fix

#158 [Fix] #154 - 1차 릴리즈 QA 2차 반영
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseEditVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/MyCourseSelectVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/PrivateCourseListView.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/SettingVC.swift
Labels: 재현🐶, Fix

#157 [Fix] #153 - 1차릴리즈이슈대응
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/AdImageCollectionViewCell.swift
Labels: 연우🐰, Fix

#160 [Fix] - 이미지 이슈 해결
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseEditVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordDetailVC.swift
Labels: 연우🐰, Fix
