Repository Runnect/Runnect-iOS, pull requests merged in 2023-01, with the labels that each got.

#9 [Add] #8 - 자물쇠 이미지 추가
  Runnect-iOS/Runnect-iOS/Global/Literal/ImageLiterals.swift
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_lock.imageset/Component 89.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_lock.imageset/Component 89@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_lock.imageset/Component 89@3x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_lock.imageset/Contents.json
Labels: Add, 세진☃️

#12 [Feat] #10 - SplashVC 및 SignInVC UI 구현
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Literal/ColorLiterals.swift
  Runnect-iOS/Runnect-iOS/Global/Supports/Base.lproj/LaunchScreen.storyboard
  Runnect-iOS/Runnect-iOS/Global/Supports/SceneDelegate.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomButton.swift
  Runnect-iOS/Runnect-iOS/Presentation/SignIn/VC/.gitkeep
  Runnect-iOS/Runnect-iOS/Presentation/SignIn/VC/SignInVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Splash/VC/SplashVC.swift
Labels: Feat, 세진☃️

#14 [Feat] #11 - MyPageVC UI 구현
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Literal/ColorLiterals.swift
  Runnect-iOS/Runnect-iOS/Global/Supports/SceneDelegate.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingHomeVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/GoalRewardInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/TabBar/TaBarController.swift
Labels: Feat, 재현🐶

#16 [Feat] #13 - 코스 그리기 메인 뷰 및 출발지 검색 뷰 UI
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Extension/UIKit+/UIImage+.swift
  Runnect-iOS/Runnect-iOS/Global/Literal/ImageLiterals.swift
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_alert.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_alert.imageset/Group 9279.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_alert.imageset/Group 9279@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_alert.imageset/Group 9279@3x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_location_point.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_location_point.imageset/Vector.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_location_point.imageset/Vector@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_location_point.imageset/Vector@3x.png
  Runnect-iOS/Runnect-iOS/Global/UIComponents/MapView/RNMapView.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/MapView/RNMarker.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/MapView/RNStartMarker.swift
  Runnect-iOS/Runnect-iOS/Global/Utils/convertLocationObject.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingHomeVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/DepartureSearchVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/Views/.gitkeep
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/Views/LocationSearchResultTVC.swift
Labels: Feat, 세진☃️

#17 [Feat] #15 - GoalRewardInfoVC UI 구현
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/GoalRewardInfoCollectionView/GoalRewardInfoCVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/GoalRewardInfoCollectionView/GoalRewardInfoModel.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/GoalRewardInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
Labels: Feat, 재현🐶

#19 [Feat] #18 - CountDownVC 구현
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Literal/FontLiterals.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CountDownVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingHomeVC.swift
Labels: Feat, 세진☃️

#22 [Docs] #21 - 리드미 작성
  README.md
Labels: Docs, 세진☃️

#23 [Feat] #20 - ActivityRecordInfo VC UI 구현
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Literal/ColorLiterals.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoTableView/ActivityRecordInfoModel.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoTableView/ActivityRecordInfoTVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoVC.swift
Labels: Feat, 재현🐶

#25 [Feat] #24 - CourseDrawingVC UI 구현
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomNavigationBar.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/MapView/RNMapView.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/MapView/RNStartMarker.swift
  Runnect-iOS/Runnect-iOS/Global/Utils/caculateStatusBarHeight.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/DepartureSearchVC.swift
Labels: Feat, 세진☃️

#28 [Feat] #27 - CustomAlertVC 구현
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Literal/ImageLiterals.swift
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_location_overlay.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_location_overlay.imageset/point 1.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_location_overlay.imageset/point 1@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_location_overlay.imageset/point 1@3x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_telescope.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_telescope.imageset/draw_img_telescope 2.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_telescope.imageset/draw_img_telescope 2@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_telescope.imageset/draw_img_telescope 2@3x.png
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomAlertVC.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomButton.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/MapView/RNMapView.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/DepartureSearchVC.swift
Labels: Feat, 세진☃️

#29 [Feat] #26 - UploadedCourseInfoVC UI 구현
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/GoalRewardInfoCollectionView/GoalRewardInfoCVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/GoalRewardInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoCollectionView/UploadedCourseInfoCVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoCollectionView/UploadedCourseInfoModel.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
Labels: Feat, 재현🐶

#39 [Fix] #39 - CourseDiscoveryVC UI 수정
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/adimage.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/adimage.imageset/Mask group.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/adimage.imageset/Mask group@2x.png
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Reuse/MapCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Reuse/MapModel.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/VC/CourseDiscoveryVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/DiscoveryDetailViewController.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/PlusDetailViewController.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/SearchResultViewController.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/UploadResultViewController.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/UploadViewController.swift
Labels: 연우💗

#40 [Feat] #37 - NicknameEditorVC UI 구현
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/NicknameEditorVC.swift
Labels: Feat, 재현🐶

#42 [Feat] #33 - RunningRecordVC UI
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Extension/UIKit+/UITextField+.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CourseDetailInfoView.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/MapView/RNMapView.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/StatsInfoView.swift
  Runnect-iOS/Runnect-iOS/Global/Utils/RNTimeFormatter.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CountDownVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/RunningRecordVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/RunTracking/VC/RunTrackingVC.swift
Labels: Feat, 세진☃️

#47 [Feat] #43 - CourseStorageVC UI 구현
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/UIComponents/ListEmptyView.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/ViewPager/PagedView/CVC/PageCVC.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/ViewPager/PagedView/PagedView.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/ViewPager/ViewPager.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/.gitkeep
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CVC/CourseListCVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/PrivateCourseListView.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/ScrapCourseListView.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/CountDownVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunTrackingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningRecordVC.swift
Labels: Feat, 세진☃️

#50 [Feat] #48 - RunningWaitingVC UI
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/PrivateCourseListView.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/ScrapCourseListView.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/CountDownVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunTrackingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningWaitingVC.swift
Labels: Feat, 세진☃️

#51 [Feat] #41 - CourseDetailVC UI 구현
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoVC.swift
Labels: Feat, 재현🐶

#53 [Feat] #49 - CourseUploadVC UI 구현
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/VC/CourseDiscoveryVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/CourseUploadVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/DiscoveryDetailViewController.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/MyCourseSelectVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/PlusDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/PlusDetailViewController.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/SearchResultVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/UploadResultViewController.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/UploadVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/UploadViewController.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CVC/CourseListCVC.swift
Labels: Feat, 연우💗

#55 [Feat] #52 - 카카오 주소 API 연결
  .gitignore
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Extension/UIKit+/UIViewController+.swift
  Runnect-iOS/Runnect-iOS/Global/Supports/AppDelegate.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomNavigationBar.swift
  Runnect-iOS/Runnect-iOS/Global/Utils/Toast.swift
  Runnect-iOS/Runnect-iOS/Global/Utils/convertLocationObject.swift
  Runnect-iOS/Runnect-iOS/Info.plist
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDetailDto/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDiscoveryDto/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDrawingDto/DepartureSearchingResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseStorageDto/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Dto/MyPageDto/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Dto/RunningDto/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Dto/SignInDto/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Foundation/BaseResponse.swift
  Runnect-iOS/Runnect-iOS/Network/Foundation/NetworkHelper.swift
  Runnect-iOS/Runnect-iOS/Network/Foundation/NetworkResult.swift
  Runnect-iOS/Runnect-iOS/Network/Model/CourseDetailModel/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Model/CourseDiscoveryModel/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Model/CourseDrawingModel/DepartureLocationModel.swift
  Runnect-iOS/Runnect-iOS/Network/Model/CourseStorageModel/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Model/MyPageModel/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Model/RunningModel/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Model/SignInModel/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Router/CourseDetailRouter/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Router/CourseDiscoveryRouter/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Router/CourseDrawingRouter/DepartureSearchingRouter.swift
  Runnect-iOS/Runnect-iOS/Network/Router/CourseStorageRouter/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Router/MyPageRouter/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Router/RunningRouter/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Router/SignInRouter/.gitkeep
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingHomeVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/DepartureSearchVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/Views/LocationSearchResultTVC.swift
Labels: Feat, 세진☃️

#62 [Feat] #59 - 개발자 인증서 등록
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
Labels: Feat, 세진☃️

#64 [Feat] #63 - 코스그리기 API 연결
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Utils/convertLocationObject.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDrawingDto/RequestDto/CourseDrawingRequestDto.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDrawingDto/ResponseDto/CourseDrawingResponseData.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDrawingDto/ResponseDto/DepartureSearchingResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Model/CourseDrawingModel/RNLocationModel.swift
  Runnect-iOS/Runnect-iOS/Network/Model/RunningModel/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Model/RunningModel/RunningModel.swift
  Runnect-iOS/Runnect-iOS/Network/Router/CourseDrawingRouter/CourseDrawingRouter.swift
  Runnect-iOS/Runnect-iOS/Network/Router/SignInRouter/.gitkeep
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/CountDownVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunTrackingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningWaitingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/SignIn/VC/SignInVC.swift
Labels: Feat, 세진☃️

#68 [Feat] #66 - 러닝 기록하기 API 연결
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Utils/RNUtils/KeychainManager.swift
  Runnect-iOS/Runnect-iOS/Global/Utils/RNUtils/RNTimeFormatter.swift
  Runnect-iOS/Runnect-iOS/Global/Utils/RNUtils/Stopwatch.swift
  Runnect-iOS/Runnect-iOS/Global/Utils/RNUtils/convertLocationObject.swift
  Runnect-iOS/Runnect-iOS/Global/Utils/Toast.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/RunningDto/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Dto/RunningDto/RequestDto/RunningRecordRequestDto.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/RunningDto/ResponseDto/RunningRecordResonseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Model/RunningModel/RunningModel.swift
  Runnect-iOS/Runnect-iOS/Network/Router/RunningRouter/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Router/RunningRouter/RunningRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunTrackingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningRecordVC.swift
Labels: Feat, 세진☃️

#71 [Feat] #67 - Course Discovery API 연결
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDiscoveryDto/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDiscoveryDto/ResponseDto/PickedMapListResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Router/CourseDiscoveryRouter/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Router/CourseDiscoveryRouter/CourseDiscoveryRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseDiscoveryVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/PrivateCourseListView.swift
Labels: Feat, 연우💗

#72 [Feat] #65 - 마이페이지 api 연결
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Network/Dto/MyPageDto/MyPageDto.swift
  Runnect-iOS/Runnect-iOS/Network/Router/MyPageRouter/MyPageRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Splash/VC/SplashVC.swift
Labels: Feat, 재현🐶

#77 [Feat] #74 - 코스 디테일 API 연결
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseStorageDto/ResponseDto/PrivateCourseResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/RunningDto/ResponseDto/CourseDetailResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Model/CourseDrawingModel/DepartureLocationModel.swift
  Runnect-iOS/Runnect-iOS/Network/Model/RunningModel/RunningModel.swift
  Runnect-iOS/Runnect-iOS/Network/Router/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Router/RunningRouter/RunningRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/CountDownVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningRecordVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningWaitingVC.swift
Labels: Feat, 세진☃️

#75 [Feat] #73 - 업로드한 코스 API 연결
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDiscoveryDto/ResponseDto/PickedMapListResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Router/MyPageRouter/MyPageRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoCollectionView/UploadedCourseInfoCVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoVC.swift
Labels: Feat, 재현🐶

#82 [Feat] #79 업로드하지 않은 내가 그린 코스 API 연결
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseStorageDto/ResponseDto/PrivateCourseNotUploadedResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseStorageDto/ResponseDto/PrivateCourseResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Router/CourseStorageRouter/CourseStorageRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseUploadVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/MyCourseSelectVC.swift
Labels: Feat, 세진☃️

#83 [Feat] #78 - 활동 기록 API 연결
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Utils/RNUtils/RNTimeFormatter.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/MyPageDto/ActivityRecordInfoDto.swift
  Runnect-iOS/Runnect-iOS/Network/Router/MyPageRouter/MyPageRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoTableView/ActivityRecordInfoTVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoCollectionView/UploadedCourseInfoCVC.swift
Labels: Feat, 재현🐶

#86 [Feat] #85 - 스크랩코스 API 연결
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomButton.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/ListEmptyView.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseStorageDto/ResponseDto/ScrapCourseResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Router/CourseStorageRouter/CourseStorageRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/ScrapCourseListView.swift
Labels: Feat, 세진☃️

#89 [Feat] #84 - 목표 보상 API 연결
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Literal/ImageLiterals.swift
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_lock.imageset/Component 89.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_lock.imageset/Component 89@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_lock.imageset/Component 89@3x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_lock.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_lock.imageset/mypage_img_stamp6.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_lock.imageset/mypage_img_stamp6@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_lock.imageset/mypage_img_stamp6@3x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_stamp_u1.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_stamp_u1.imageset/mypage_img_stamp7.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_stamp_u1.imageset/mypage_img_stamp7@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_stamp_u1.imageset/mypage_img_stamp7@3x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_stamp_u2.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_stamp_u2.imageset/mypage_img_stamp8.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_stamp_u2.imageset/mypage_img_stamp8@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_stamp_u2.imageset/mypage_img_stamp8@3x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_stamp_u3.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_stamp_u3.imageset/mypage_img_stamp9.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_stamp_u3.imageset/mypage_img_stamp9@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_stamp_u3.imageset/mypage_img_stamp9@3x.png
  Runnect-iOS/Runnect-iOS/Network/Dto/MyPageDto/GoalRewardInfoDto.swift
  Runnect-iOS/Runnect-iOS/Network/Router/MyPageRouter/MyPageRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/GoalRewardInfoCollectionView/GoalRewardInfoCVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/GoalRewardInfoCollectionView/GoalRewardInfoModel.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/GoalRewardInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
Labels: Feat, 재현🐶

#87 [Feat] #81 - 코스업로드하기 API 연결 완료
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Extension/Foundation+/Encodable+.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDiscoveryDto/RequestDto/CourseUploadingRequestDto.swift
  Runnect-iOS/Runnect-iOS/Network/Router/CourseDiscoveryRouter/CourseUploadingRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseSearchVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseUploadVC.swift
Labels: Feat, 연우🐰

#92 [Feat] #88 - CourseDetailVC API 연결
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDetailDto/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDetailDto/ResponseDto/UploadedCourseDetailResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDiscoveryDto/ResponseDto/PickedMapListResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Router/CourseDetailRouter/.gitkeep
  Runnect-iOS/Runnect-iOS/Network/Router/CourseDetailRouter/UploadedCourseDetailRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/.gitkeep
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseDiscoveryVC.swift
Labels: Feat, 세진☃️

#93 [Feat] #90 - 마이페이지 닉네임 변경 API 연결
  Runnect-iOS/Runnect-iOS/Network/Router/MyPageRouter/MyPageRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/NicknameEditorVC.swift
Labels: Feat, 재현🐶

#94 [Feat] #91 - CourseSearchVC API 연결 완료
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseSearchVC.swift
Labels: Feat, 연우🐰

#96 [Fix] #95 - 헤더 변경
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_person.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_person.imageset/Group 9469.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_person.imageset/Group 9469@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_person.imageset/Group 9469@3x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_person.imageset/login_me 1.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_person.imageset/login_me 1@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_person.imageset/login_me 1@3x.png
  Runnect-iOS/Runnect-iOS/Network/Router/MyPageRouter/MyPageRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/GoalRewardInfoCollectionView/GoalRewardInfoModel.swift
Labels: Feat, 재현🐶

#98 [Feat] #97 - 스크랩 API 연결
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDiscoveryDto/ResponseDto/PickedMapListResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Router/CourseDetailRouter/UploadedCourseDetailRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseDiscoveryVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseSearchVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CVC/CourseListCVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/ScrapCourseListView.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
Labels: Feat, 세진☃️, 연우🐰, 재현🐶

#102 [Docs] #101 - 최종과제 README 수정
  README.md
Labels: Docs, 세진☃️, 연우🐰, 재현🐶

#104 [Fix] #103 - QA 반영
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/DepartureSearchVC.swift
Labels: 세진☃️, 연우🐰, 재현🐶, Fix

#106 [Fix] #105 - 2차 QA 반영
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/AppIcon.appiconset/runnect logo-01 1.png
  Runnect-iOS/Runnect-iOS/Global/Utils/Toast.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CVC/CourseListCVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/NicknameEditorVC.swift
Labels: 세진☃️, 연우🐰, 재현🐶, Fix

#108 [Fix] #107 - 함수 선언에서 띄어쓰기 수정
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/NicknameEditorVC.swift
Labels: 세진☃️, Fix
