Repository Runnect/Runnect-iOS, pull requests merged in 2023-04, with the labels that each got.

#122 [Feat] #121 - 지도 영역 가이드 추가
  Runnect-iOS/.swiftlint.yml
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS.xcodeproj/xcshareddata/xcschemes/Runnect-iOS.xcscheme
  Runnect-iOS/Runnect-iOS/Global/Extension/UIKit+/UIImage+.swift
  Runnect-iOS/Runnect-iOS/Global/Literal/ImageLiterals.swift
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_logo_circle.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_logo_circle.imageset/runnect logo-01 1 1.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_logo_circle.imageset/runnect logo-01 1 1@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_logo_circle.imageset/runnect logo-01 1 1@3x.png
  Runnect-iOS/Runnect-iOS/Global/UIComponents/GuideView.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/MapView/RNMapView.swift
  Runnect-iOS/Runnect-iOS/Global/Utils/RNUtils/UserManager.swift
  Runnect-iOS/Runnect-iOS/Global/Utils/adjusted+.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/MyPageDto/ActivityRecordInfoDto.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/MyPageDto/MyPageDto.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/SignInDto/ResponseDto/SignInResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Router/AuthRouter.swift
  Runnect-iOS/Runnect-iOS/Network/Router/CourseRouter.swift
  Runnect-iOS/Runnect-iOS/Network/Router/PublicCourseRouter.swift
  Runnect-iOS/Runnect-iOS/Network/Router/UserRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingHomeVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/SignIn/VC/NickNameSetUpVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/SignIn/VC/SignInSocialLoginVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Splash/VC/SplashVC.swift
Labels: Feat, 세진☃️

#124 [Feat] #123 - 자동로그인 구현
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Literal/ImageLiterals.swift
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_apple_login.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_apple_login.imageset/Group 9514.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_apple_login.imageset/Group 9514@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_apple_login.imageset/Group 9514@3x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_kakao_login.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_kakao_login.imageset/Kakao Login.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_kakao_login.imageset/Kakao Login@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/img_kakao_login.imageset/Kakao Login@3x.png
  Runnect-iOS/Runnect-iOS/Global/Utils/RNUtils/UserManager.swift
  Runnect-iOS/Runnect-iOS/Network/Dto/SignInDto/ResponseDto/GetNewTokenResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Router/AuthRouter.swift
  Runnect-iOS/Runnect-iOS/Network/Router/CourseRouter.swift
  Runnect-iOS/Runnect-iOS/Network/Router/PublicCourseRouter.swift
  Runnect-iOS/Runnect-iOS/Network/Router/RecordRouter.swift
  Runnect-iOS/Runnect-iOS/Network/Router/ScrapRouter.swift
  Runnect-iOS/Runnect-iOS/Network/Router/StampRouter.swift
  Runnect-iOS/Runnect-iOS/Network/Router/UserRouter.swift
  Runnect-iOS/Runnect-iOS/Network/Service/AuthInterceptor.swift
  Runnect-iOS/Runnect-iOS/Network/Service/Providers.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseDiscoveryVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseSearchVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseUploadVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/MyCourseSelectVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/DepartureSearchVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/GoalRewardInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/NicknameEditorVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningRecordVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningWaitingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/SignIn/VC/NickNameSetUpVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/SignIn/VC/SignInSocialLoginVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Splash/VC/SplashVC.swift
Labels: Feat, 세진☃️

#125 [Feat] #117 - 신고폼 구현
  Runnect-iOS/Runnect-iOS/Global/Literal/ImageLiterals.swift
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_more.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_more.imageset/Frame 9479.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_more.imageset/Frame 9479@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_more.imageset/Frame 9479@3x.png
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomNavigationBar.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
Labels: Feat, 연우🐰

#128 [Refactor] #127 - 마이페이지 UI 수정
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/DeleteAccountVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/LogoutVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/PersoanlInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/PersonalInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/SettingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/TermsOfServiceVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/WithdrawVC.swift
Labels: Refactor, 재현🐶
