Repository Runnect/Runnect-iOS, pull requests merged in 2024-03, with the labels that each got.

#258 [Fix] #257 - 레이아웃 코드를 변경하였습니다.
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Extension/UIKit+/UIViewController+.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CourseDetailInfoView.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomAlertVC.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomBottomSheetVC.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomButton.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomNavigationBar.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/GuideView.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/ListEmptyView.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/MapView/RNMapView.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/RNAlertVC.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/StatsInfoView.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/ViewPager/PagedView/CVC/PageCVC.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/ViewPager/PagedView/PagedView.swift
  Runnect-iOS/Runnect-iOS/Global/UIComponents/ViewPager/ViewPager.swift
  Runnect-iOS/Runnect-iOS/Network/Router/RecordRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseEditVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/AdImageCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/MarathonMapCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/MarathonTitleCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/TitleCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseDiscoveryVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseSearchVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/CourseUploadVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/VC/MyCourseSelectVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingHomeVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/DepartureSearchVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/Views/LocationSearchResultTVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/Views/LocationSelectView.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CVC/CourseListCVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/PrivateCourseListView.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/Views/CourseListView/ScrapCourseListView.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoTableView/ActivityRecordInfoTVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/ActivityRecordInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/GoalRewardInfoCollectionView/GoalRewardInfoCVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/GoalRewardInfoCollectionView/GoalRewardTitleCVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/GoalRewardInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoCollectionView/UploadedCourseInfoCVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/InfoVC/UploadedCourseInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/MyPageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/NicknameEditorVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/PersonalInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/SettingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/CountDownVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunTrackingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningRecordVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningWaitingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/SignIn/VC/NickNameSetUpVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/SignIn/VC/SignInSocialLoginVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Splash/VC/SplashVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/TabBar/TabBarController.swift
  Runnect-iOS/Runnect-iOS/Presentation/UserProfile/CollectionViewCell/UserProgressCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/UserProfile/UserProfileVC.swift
Labels: Fix, 명진😼

#261 [Feat] #259 - 개인 코스 공유 기능을 추가 하였습니다.
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Extension/UIKit+/UIViewController+.swift
  Runnect-iOS/Runnect-iOS/Global/Supports/SceneDelegate.swift
  Runnect-iOS/Runnect-iOS/Info.plist
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseStorageDto/ResponseDto/PrivateCourseResponseDto.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningWaitingVC.swift
  Runnect-iOS/fastlane/Matchfile
Labels: Feat, Refactor, 명진😼

#264 [Fix] #262 - 사용자 경험 개선을 위한 네이버맵 수정
  .github/PULL_REQUEST_TEMPLATE.md
  Runnect-iOS/.swiftlint.yml
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Literal/ImageLiterals.swift
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_location_overlay_direction.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_location_overlay_direction.imageset/point 1.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_location_overlay_direction.imageset/point 1@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_location_overlay_direction.imageset/point 1@3x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_location_overlay_normal.imageset/Contents.json
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_location_overlay_normal.imageset/Group 9581.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_location_overlay_normal.imageset/Group 9581@2x.png
  Runnect-iOS/Runnect-iOS/Global/Resource/Assets.xcassets/ic_location_overlay_normal.imageset/Group 9581@3x.png
  Runnect-iOS/Runnect-iOS/Global/UIComponents/MapView/RNMapView.swift
  Runnect-iOS/Runnect-iOS/Info.plist
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDrawingDto/ResponseDto/TmapAddressSearchingResponseDto.swift
  Runnect-iOS/Runnect-iOS/Network/Router/CourseDrawingRouter/DepartureSearchingRouter.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDrawing/VC/CourseDrawingVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningWaitingVC.swift
Labels: Fix, 명진😼

#266 [Feat] #263 - 보관함 페이지 간헐적 버그 수정 및 리팩토링
  Runnect-iOS/Runnect-iOS/Global/UIComponents/CustomBottomSheetVC.swift
  Runnect-iOS/Runnect-iOS/Network/Service/Providers.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseStorage/VC/CourseStorageVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/Running/VC/RunningWaitingVC.swift
Labels: Refactor, Fix, 소진🍊
