Repository Runnect/Runnect-iOS, pull requests merged in 2024-02, with the labels that each got.

#251 [Feat] #206 - remote config 추가했습니다
  Runnect-iOS/Podfile
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Global/Supports/AppDelegate.swift
Labels: Feat, 소진🍊

#252 [Fix] #250 - 파이어베이스 공용계정으로 이전 하였습니다.
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Network/Dto/CourseDrawingDto/ResponseDto/KakaoAddressSearchingResponseDto.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDetail/VC/CourseDetailVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/CourseDiscovery/Views/MarathonMapCollectionViewCell.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/PersoanlInfoVC.swift
  Runnect-iOS/Runnect-iOS/Presentation/MyPage/VC/SettingVC/TermsOfServiceVC.swift
  Runnect-iOS/Runnect-iOS/Runnect-iOS.entitlements
  Runnect-iOS/Runnect-iOS/Runnect-iOSDebug.entitlements
  Runnect-iOS/fastlane/Matchfile
Labels: Fix, 명진😼

#254 [Setting] #253 - Remote Config 세팅 작업을 완료 하였습니다.
  Runnect-iOS/Podfile.lock
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS.xcodeproj/xcshareddata/xcschemes/Runnect-iOS.xcscheme
  Runnect-iOS/Runnect-iOS/Global/Supports/AppDelegate.swift
  Runnect-iOS/Runnect-iOS/Network/Foundation/NetworkHelper.swift
  Runnect-iOS/Runnect-iOS/Network/Foundation/NetworkResult.swift
  Runnect-iOS/Runnect-iOS/Presentation/Splash/VC/SplashVC.swift
  Runnect-iOS/fastlane/Matchfile
Labels: Setting, 명진😼

#256 [Setting] #255 - release 2.0.0
  Runnect-iOS/Runnect-iOS.xcodeproj/project.pbxproj
  Runnect-iOS/Runnect-iOS/Info.plist
Labels: Setting, 명진😼
